version: "3.7"

services:
  postgres:
    container_name: postgres-blueprint
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blueprint
      - POSTGRES_USER=blueprint
      - POSTGRES_PASSWORD=blueprint