site_name: arch-blueprint-java
site_url: https://vondacho.github.io/arch-blueprint-java
repo_url: https://github.com/vondacho/arch-blueprint-java/
repo_name: GitHub repository
docs_dir: doc/tech

nav:
  - Home: index.md
  - API: api/
  - Architecture: architecture.md
  - Testing: testing.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: True

theme: material

extra_css:
  - stylesheets/colors.css