name: publish release

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

      - name: Release version
        id: release
        run: echo "version=$(echo ${{ github.ref }} | cut -d / -f3)" >> ${{ github.output }}

      - name: Build app maps
        run: ./gradlew appmap test

      - name: Build main branch
        run: ./gradlew -Pversion=${{ steps.release.outputs.version }} build

      - name: Build documentation
        uses: ./gradlew mkdocs

      - name: Publish documentation
        uses: ./.github/actions/mkdocs-publish
