name: publish release

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

      - name: Setup Build
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/setup-gradle.sh

      - name: Release version
        id: release
        run: echo "version=$(echo ${{ github.ref }} | cut -d / -f3)" >> ${{ github.output }}

      - name: Build app maps
        run: ./gradlew appmap test

      - name: Build main branch
        run: ./gradlew -Pversion=${{ steps.release.outputs.version }} build

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Prepare documentation
        run: ./gradlew allureAggregateReport plantumlAll generateSwaggerUI

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Build and publish documentation to GH pages
        run: ./gradlew -Pversion=${{ steps.release.outputs.version }} mkdocsPublish
