name: publish release documentation

on:
  workflow_dispatch: # Allow to manually trigger the pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Deploy to GH pages
        uses: ./.github/actions/mkdocs-publish
